"""event and image table insert

Revision ID: d2af5f71cb4e
Revises: 7035d20fb8c0
Create Date: 2025-04-24 00:01:02.335481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2af5f71cb4e'
down_revision: Union[str, None] = '7035d20fb8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Beedier Media ID', sa.Integer(), nullable=True),
    sa.Column('Image URL', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Image URL')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Event URL', sa.String(), nullable=False),
    sa.Column('Website Name', sa.String(), nullable=False),
    sa.Column('Web Content', sa.Text(), nullable=True),
    sa.Column('Title', sa.Text(), nullable=True),
    sa.Column('Index Intro', sa.Text(), nullable=True),
    sa.Column('Intro', sa.Text(), nullable=True),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('Dates', sa.String(), nullable=True),
    sa.Column('Date Order', sa.String(length=8), nullable=True),
    sa.Column('Location', sa.String(), nullable=True),
    sa.Column('Cost', sa.String(), nullable=True),
    sa.Column('Generated Content', sa.Boolean(), nullable=False),
    sa.Column('Beedier Event ID', sa.Integer(), nullable=True),
    sa.Column('Published', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Event URL')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('image')
    # ### end Alembic commands ###
