"""created all tables

Revision ID: f26869caf65b
Revises: 
Create Date: 2026-02-04 14:58:37.556706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26869caf65b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('remote_category_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remote_category_id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('remote_media_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_url', sa.String(), nullable=False),
    sa.Column('website_name', sa.String(), nullable=False),
    sa.Column('web_content', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('index_intro', sa.Text(), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('dates', sa.String(), nullable=True),
    sa.Column('date_order', sa.String(length=8), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('generated_content', sa.Boolean(), nullable=False),
    sa.Column('remote_event_id', sa.Integer(), nullable=True),
    sa.Column('publish_status', sa.Enum('UNSYNCED', 'DRAFT', 'PUBLISHED', name='publish_status_enum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_url'), 'events', ['event_url'], unique=True)
    op.create_index(op.f('ix_events_remote_event_id'), 'events', ['remote_event_id'], unique=False)
    op.create_index(op.f('ix_events_website_name'), 'events', ['website_name'], unique=False)
    op.create_table('event_category_association',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_category_association')
    op.drop_index(op.f('ix_events_website_name'), table_name='events')
    op.drop_index(op.f('ix_events_remote_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_url'), table_name='events')
    op.drop_table('events')
    op.drop_table('images')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
